/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { NFTContract, NFTContractInterface } from "../NFTContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class NFTContract__factory {
  static readonly abi = _abi;
  static createInterface(): NFTContractInterface {
    return new utils.Interface(_abi) as NFTContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTContract {
    return new Contract(address, _abi, signerOrProvider) as NFTContract;
  }
}
